public class main_perpustakaan {
    public static void main(String[] args) {
        perpustakaan teknologi1 = new perpustakaan();
        teknologi1.setJudulBuku("Introduction to Java Programming, Comprehensive Version, 10th Edition");
        teknologi1.setKategoriBuku("Teknologi");
        teknologi1.setPenulisBuku(new String[]{"Y. Daniel Liang"});
        teknologi1.setTahunTerbitBuku(2015);
        perpustakaan teknologi2 = new perpustakaan();
        teknologi2.setJudulBuku("Java How to Program, Tenth Edition, Late Objects Version");
        teknologi2.setKategoriBuku("Teknologi");
        teknologi2.setPenulisBuku(new String[]{"Paul Deitel", "Harvey Deitel"});
        teknologi2.setTahunTerbitBuku(2014);
        perpustakaan teknologi3 = new perpustakaan();
        teknologi3.setJudulBuku("Operating System Concepts, Tenth Edition");
        teknologi3.setKategoriBuku("Teknologi");
        teknologi3.setPenulisBuku(new String[]{"Abraham Silberschatz","Peter Baer Galvin", "Greg Gagne"});
        teknologi3.setTahunTerbitBuku(2018);
        perpustakaan teknologi4 = new perpustakaan();
        teknologi4.setJudulBuku("Operating System: Internals and Design Principles, Ninth Edition");
        teknologi4.setKategoriBuku("Teknologi");
        teknologi4.setPenulisBuku(new String[]{"William Stallings"});
        teknologi4.setTahunTerbitBuku(2018);
        perpustakaan teknologi5 = new perpustakaan();
        teknologi5.setJudulBuku("Fundamentals of Information Systems, Eight Edition");
        teknologi5.setKategoriBuku("Teknologi");
        teknologi5.setPenulisBuku(new String[]{"Ralph M. Stair","George W. Reynolds"});
        teknologi5.setTahunTerbitBuku(2017);

        perpustakaan filsafat1 = new perpustakaan();
        filsafat1.setJudulBuku("Filosofi Teras");
        filsafat1.setKategoriBuku("Filsafat");
        filsafat1.setPenulisBuku(new String[]{"Henry Manampiring"});
        filsafat1.setTahunTerbitBuku(2018);
        perpustakaan filsafat2 = new perpustakaan();
        filsafat2.setJudulBuku("The Meaning of Human Existence");
        filsafat2.setKategoriBuku("Filsafat");
        filsafat2.setPenulisBuku(new String[]{"Edward O. Wilson"});
        filsafat2.setTahunTerbitBuku(2014);
        perpustakaan filsafat3 = new perpustakaan();
        filsafat3.setJudulBuku("The Midnight Library");
        filsafat3.setKategoriBuku("Filsafat");
        filsafat3.setPenulisBuku(new String[]{"Matt Haig"});
        filsafat3.setTahunTerbitBuku(2020);
        perpustakaan filsafat4 = new perpustakaan();
        filsafat4.setJudulBuku("On Being");
        filsafat4.setKategoriBuku("Filsafat");
        filsafat4.setPenulisBuku(new String[]{"Peter Atkins"});
        filsafat4.setTahunTerbitBuku(2011);
        perpustakaan filsafat5 = new perpustakaan();
        filsafat5.setJudulBuku("Dunia Sophie");
        filsafat5.setKategoriBuku("Filsafat");
        filsafat5.setPenulisBuku(new String[]{"Jostein Gaarder"});
        filsafat5.setTahunTerbitBuku(1991);
        
        perpustakaan sejarah1 = new perpustakaan();
        sejarah1.setJudulBuku("Sapiens: A Brief History of Humankind");
        sejarah1.setKategoriBuku("Sejarah");
        sejarah1.setPenulisBuku(new String[]{"Yuval Noah Harari"});
        sejarah1.setTahunTerbitBuku(2011);
        perpustakaan sejarah2 = new perpustakaan();
        sejarah2.setJudulBuku("Sejarah Dunia Yang Disembunyikan");
        sejarah2.setKategoriBuku("Sejarah");
        sejarah2.setPenulisBuku(new String[]{"Jonathan Black"});
        sejarah2.setTahunTerbitBuku(2007);
        perpustakaan sejarah3 = new perpustakaan();
        sejarah3.setJudulBuku("Genghis Khan and the Making of the Modern World");
        sejarah3.setKategoriBuku("Sejarah");
        sejarah3.setPenulisBuku(new String[]{"Jack Weatherford"});
        sejarah3.setTahunTerbitBuku(2004);
        perpustakaan sejarah4 = new perpustakaan();
        sejarah4.setJudulBuku("A Short History of Nearly Everything");
        sejarah4.setKategoriBuku("Sejarah");
        sejarah4.setPenulisBuku(new String[]{"Bill Bryson"});
        sejarah4.setTahunTerbitBuku(2003);
        perpustakaan sejarah5 = new perpustakaan();
        sejarah5.setJudulBuku("The Silk Roads: A New History of the World");
        sejarah5.setKategoriBuku("Sejarah");
        sejarah5.setPenulisBuku(new String[]{"Peter Frankopan"});
        sejarah5.setTahunTerbitBuku(2015);

        perpustakaan agama1 = new perpustakaan();
        agama1.setJudulBuku("Buku Ajar Pendidikan Agama Islam Edisi Revisi");
        agama1.setKategoriBuku("Agama");
        agama1.setPenulisBuku(new String[]{"Prof. Dr. Thohir Luth, M.A.","Dr. Nur Chanifah, M.Pd.I", "Khalid Rahman, M.Pd.I", "Mokhamad Rohma Rozikin, M.Pd."});
        agama1.setTahunTerbitBuku(2007);
        perpustakaan agama2 = new perpustakaan();
        agama2.setJudulBuku("The Case for God");
        agama2.setKategoriBuku("Agama");
        agama2.setPenulisBuku(new String[]{"Karen Armstrong"});
        agama2.setTahunTerbitBuku(2009);
        perpustakaan agama3 = new perpustakaan();
        agama3.setJudulBuku("The Evolution of God");
        agama3.setKategoriBuku("Agama");
        agama3.setPenulisBuku(new String[]{"Robert Wright"});
        agama3.setTahunTerbitBuku(2009);
        perpustakaan agama4 = new perpustakaan();
        agama4.setJudulBuku("Religion and the Rise of Capitalism");
        agama4.setKategoriBuku("Agama");
        agama4.setPenulisBuku(new String[]{"Benjamin M. Friedman"});
        agama4.setTahunTerbitBuku(2021);
        perpustakaan agama5 = new perpustakaan();
        agama5.setJudulBuku("The Varieties of Religious Experience: A Study in Human Nature");
        agama5.setKategoriBuku("Agama");
        agama5.setPenulisBuku(new String[]{"William James"});
        agama5.setTahunTerbitBuku(2002);

        perpustakaan psikologi1 = new perpustakaan();
        psikologi1.setJudulBuku("The Power of Habit: Why We Do What We Do in Life and Business");
        psikologi1.setKategoriBuku("Psikologi");
        psikologi1.setPenulisBuku(new String[]{"Charles Duhigg"});
        psikologi1.setTahunTerbitBuku(2012);
        perpustakaan psikologi2 = new perpustakaan();
        psikologi2.setJudulBuku("Thinking, Fast and Slow");
        psikologi2.setKategoriBuku("Psikologi");
        psikologi2.setPenulisBuku(new String[]{"Daniel Kahneman"});
        psikologi2.setTahunTerbitBuku(2011);
        perpustakaan psikologi3 = new perpustakaan();
        psikologi3.setJudulBuku("Atomic Habbits: An Easy & Proven Way to Build Good Habits & Break Bad Ones");
        psikologi3.setKategoriBuku("Psikologi");
        psikologi3.setPenulisBuku(new String[]{"James Clear"});
        psikologi3.setTahunTerbitBuku(2018);
        perpustakaan psikologi4 = new perpustakaan();
        psikologi4.setJudulBuku("Grit: The Power of Passion and Perseverance");
        psikologi4.setKategoriBuku("Psikologi");
        psikologi4.setPenulisBuku(new String[]{"Angela Duckworth"});
        psikologi4.setTahunTerbitBuku(2016);
        perpustakaan psikologi5 = new perpustakaan();
        psikologi5.setJudulBuku("The Paradox of Choice: Why More Is less");
        psikologi5.setKategoriBuku("Psikologi");
        psikologi5.setPenulisBuku(new String[]{"Barry Schwartz"});
        psikologi5.setTahunTerbitBuku(2004);

        perpustakaan politik1 = new perpustakaan();
        politik1.setJudulBuku("How Democracies Die");
        politik1.setKategoriBuku("Politik");
        politik1.setPenulisBuku(new String[]{"Steven Levitsky","Daniel Ziblatt"});
        politik1.setTahunTerbitBuku(2018);
        perpustakaan politik2 = new perpustakaan();
        politik2.setJudulBuku("Why Nations FailL The Origins of Power, Prosperity, and Poverty");
        politik2.setKategoriBuku("Politik");
        politik2.setPenulisBuku(new String[]{"Daron Acemoglu", "James A. Robinson"});
        politik2.setTahunTerbitBuku(2012);
        perpustakaan politik3 = new perpustakaan();
        politik3.setJudulBuku("Democracy in Chains: The Deep History of the Radical Right's Stealth Plan for America");
        politik3.setKategoriBuku("Politik");
        politik3.setPenulisBuku(new String[]{"Nancy MacLean"});
        politik3.setTahunTerbitBuku(2017);
        perpustakaan politik4 = new perpustakaan();
        politik4.setJudulBuku("The Fifth Risk");
        politik4.setKategoriBuku("Politik");
        politik4.setPenulisBuku(new String[]{"Michael Lewis"});
        politik4.setTahunTerbitBuku(2018);
        perpustakaan politik5 = new perpustakaan();
        politik5.setJudulBuku("The Light That Failed: A Reckogning");
        politik5.setKategoriBuku("Politik");
        politik5.setPenulisBuku(new String[]{"Ivan Krastev","Stephen Holmes"});
        politik5.setTahunTerbitBuku(2019);

        perpustakaan fiksi1 = new perpustakaan();
        fiksi1.setJudulBuku("The Night Circus");
        fiksi1.setKategoriBuku("Fiksi");
        fiksi1.setPenulisBuku(new String[]{"Erin Morgenstern"});
        fiksi1.setTahunTerbitBuku(2011);
        perpustakaan fiksi2 = new perpustakaan();
        fiksi2.setJudulBuku("The Underground Railroad");
        fiksi2.setKategoriBuku("Fiksi");
        fiksi2.setPenulisBuku(new String[]{"Colson Whitehead"});
        fiksi2.setTahunTerbitBuku(2016);
        perpustakaan fiksi3 = new perpustakaan();
        fiksi3.setJudulBuku("Babel: An Arcane History");
        fiksi3.setKategoriBuku("Fiksi");
        fiksi3.setPenulisBuku(new String[]{"R.F. Kuang"});
        fiksi3.setTahunTerbitBuku(2022);
        perpustakaan fiksi4 = new perpustakaan();
        fiksi4.setJudulBuku("Sea of Tranquility");
        fiksi4.setKategoriBuku("Fiksi");
        fiksi4.setPenulisBuku(new String[]{"Emily St. John mandel"});
        fiksi4.setTahunTerbitBuku(2022);
        perpustakaan fiksi5 = new perpustakaan();
        fiksi5.setJudulBuku("Klara and the Sun");
        fiksi5.setKategoriBuku("Fiksi");
        fiksi5.setPenulisBuku(new String[]{"Kazuo Ishiguro"});
        fiksi5.setTahunTerbitBuku(2021);

        perpustakaan perpustakaan = new perpustakaan();
        perpustakaan.setNamaPerpustakaan("Universitas X");
        perpustakaan.awalan();

        teknologi1.menampilkanKategori();
        teknologi1.dataBuku();
        teknologi2.dataBuku();
        teknologi3.dataBuku();
        teknologi4.dataBuku();
        teknologi5.dataBuku();
        filsafat1.menampilkanKategori();
        filsafat1.dataBuku();
        filsafat2.dataBuku();
        filsafat3.dataBuku();
        filsafat4.dataBuku();
        filsafat5.dataBuku();
        sejarah1.menampilkanKategori();
        sejarah1.dataBuku();
        sejarah2.dataBuku();
        sejarah3.dataBuku();
        sejarah4.dataBuku();
        sejarah5.dataBuku();
        agama1.menampilkanKategori();
        agama1.dataBuku();
        agama2.dataBuku();
        agama3.dataBuku();
        agama4.dataBuku();
        agama5.dataBuku();
        psikologi1.menampilkanKategori();
        psikologi1.dataBuku();
        psikologi2.dataBuku();
        psikologi3.dataBuku();
        psikologi4.dataBuku();
        psikologi5.dataBuku();
        politik1.menampilkanKategori();
        politik1.dataBuku();
        politik2.dataBuku();
        politik3.dataBuku();
        politik4.dataBuku();
        politik5.dataBuku();
        fiksi1.menampilkanKategori();
        fiksi1.dataBuku();
        fiksi2.dataBuku();
        fiksi3.dataBuku();
        fiksi4.dataBuku();
        fiksi5.dataBuku();
        
        perpustakaan.akhiran();
    }
}
